### ISSUE TITLE
Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by acdickinson** [mendixlabs/listview-filter#3]
With Mendix 7.8.0, the widget throws an error.

If you visit a page where the listview filter is present, the filter renders fine. When you navigate to another page, an error is thrown. If you navigate again to the page with the listview filter, the widget does not render anymore with the following error  **drop-down-filter: unable to find a listview with to attach to**

The error in the console shows:
`Invariant Violation: Minified React error #188; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Only in Firefox the stacktrace is found and it refers to the listview filter widget:

**Stacktrace**:
`i@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:399713
x@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:402452
Ai@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:436061
findHostInstance@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:513056
@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:512157
Cd@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:491246
i</p</e.prototype.connectToListView@http://localhost:8080/widgets/com/mendix/widget/custom/dropdownfilter/DropDownFilter.js?636455657713425792:6:3018
hitch/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:26706
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:54686
navigateTo/this._pendingRequest<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:50:33517
u@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48811
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48737
d/this.resolve@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49755
l@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49181
c/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49089
u@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48811
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48737
d/this.resolve@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49755
l@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49181
u@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48942
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48737
d/this.resolve@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49755
r</</</<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:50:35866
u@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48811
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48737
d/this.resolve@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49755
u@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48811
s@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:48737
d/this.resolve@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:49755
r/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:50:32164
o@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137809
o@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137809
hitch/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:26706
o@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137809
hitch/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:26706
o@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137809
e.exports.collect@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137992
e.exports.applyContext@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:19:7060
passContext@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:19:1875
refresh/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:74201
_applyConditions/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:73886
update/</<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:236781
_applyConditions/i<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:73771
update/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:236757
o@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137809
e.exports.collect@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:137992
e.exports.ready@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:19:7003
update@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:236729
_applyConditions@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:73797
refresh@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:74161
n@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:73114
_update/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:73191
callback@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:242252
b@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:613019
i/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:5:136088
T/</<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:177436
T/<@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:177306
c@http://localhost:8080/mxclientsystem/mxui/mxui.js?636455657713425792:43:181163
  mxui.js:5:140957
`

**Comment by Andries-Smit** [comment]
Dear Dickinson

This widget is replaced by the list view controls, it contains the list view filter and many more. 
https://appstore.home.mendix.com/link/app/105694/

Please re-open an issue on when this issue reoccurs
https://github.com/mendixlabs/list-view-controls/issues

Kind regards, 
Andries
